// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace youtube_xml_dotnet.Migrations
{
    [DbContext(typeof(VideoContext))]
    partial class VideoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Video", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("thumbnail")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("uploadDate")
                        .HasColumnType("TEXT");

                    b.Property<uint>("views")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("videos");
                });
#pragma warning restore 612, 618
        }
    }
}
